name: XCS224N
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.23.2
  - scipy=1.7.3
  - scikit-learn=1.1.1
  - matplotlib=3.5.3
  - tqdm=4.64.1
  - docopt=0.6.2
  - notebook
  - pip=22.1.2